Project_62133199/Controllers/Home_62133199Controller.cs
using PagedList;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using Project_62133199.Models;

namespace Project_62133199.Controllers
{
    public class Home_62133199Controller : Controller
    {
        //Tao 1 doi tuong chua toan bo CSDL tu dbWeb ban giay
        dbShopGiayDataContext data = new dbShopGiayDataContext();
        #region Trang chủ
        #region index
        public ActionResult Index(int? page)
        {
            int pageSize = 9;
            int pageNum = (page ?? 1);
            var giayton = from s in data.SANPHAMs
                          where s.TrangThai == true
                          select s;
            return PartialView(giayton.ToPagedList(pageNum, pageSize));
        }
        #endregion
        #region danh sách sản phẩm
        public ActionResult ListSanPham(int? page)
        {
            int pageSize = 9;
            int pageNum = (page ?? 1);
            var giayton = from s in data.SANPHAMs join lg in data.LOAIGIAYs on s.MaLoai equals lg.MaLoai 
                          where s.TrangThai == true && lg.TrangThai == true
                          select s;
            return PartialView(giayton.ToPagedList(pageNum, pageSize));
        }
        #endregion
        #region lấy giày mới
        private List<SANPHAM> LayGiayMoi(int count)
        {
            return data.SANPHAMs.OrderByDescending(a => a.NgayCapNhat).Take(count).ToList();
        }
        #endregion
        #region giày mới
        public ActionResult GiayMoi()
        {
            var giaymoi = LayGiayMoi(5);
            return PartialView(giaymoi);
        }
        #endregion
        #region số lượng giày tồn
        private List<SANPHAM> SoLuongTonGiay(int count)
        {
            return data.SANPHAMs.OrderByDescending(a => a.SoLuongTon).Take(count).ToList();
        }
        #endregion
        #region chi tiết
        public ActionResult ChiTietSanPham(int id)
        {
            var chitietsanpham = (from s in data.SANPHAMs
                                  where s.MaGiay == id
                                  join lg in data.LOAIGIAYs
                                  on s.MaLoai equals lg.MaLoai
                                  join th in data.THUONGHIEUs
                                  on s.MaThuongHieu equals th.MaThuongHieu
                                  select new CTSP_62133199
                                  {
                                      MaGiay = s.MaGiay,
                                      TenGiay = s.TenGiay,
                                      Size = s.Size,
                                      AnhBia = s.AnhBia,
                                      GiaBan = s.GiaBan,
                                      MaThuongHieu = th.MaThuongHieu,
                                      TenThuongHieu = th.TenThuongHieu,
                                      MaLoai = lg.MaLoai,
                                      TenLoai = lg.TenLoai,
                                      ThoiGianBaoHanh = (int)s.ThoiGianBaoHanh,
                                  });
            return View(chitietsanpham.Single());
        }

        #endregion
        #region thương hiệu
        public ActionResult ThuongHieu()
        {
            var thuonghieu = (from s in data.THUONGHIEUs select s);
            return PartialView(thuonghieu);
        }
        #endregion
        #region sản phẩm theo thương hiệu
        public ActionResult SPTheoThuongHieu(int id, int? page)
        {
            int pageSize = 9;
            int pageNum = (page ?? 1);
            var sanpham = from s in data.SANPHAMs where (s.MaThuongHieu == id && s.TrangThai == true) select s;
            return View(sanpham.ToPagedList(pageNum, pageSize));
        }
        #endregion
        #region giày nam
        public ActionResult GiayNam()
        {
            var GiayNam = from s in data.LOAIGIAYs 
                          where s.GioiTinh == true && s.TrangThai == true
                          select s;
            return PartialView(GiayNam);
        }
        #endregion
        #region giày nữ

        public ActionResult GiayNu()
        {
            var GiayNu = from s in data.LOAIGIAYs
                         where s.GioiTinh == false && s.TrangThai == true
                         select s;
            return PartialView(GiayNu);
        }
        #endregion
        #region giới tính
        public ActionResult SPTheoGioiTinh(int id, int? page)
        {
            int pageSize = 9;
            int pageNum = (page ?? 1);
            var sanpham = from s in data.SANPHAMs where (s.MaLoai == id && s.TrangThai == true) select s;
            return View(sanpham.ToPagedList(pageNum, pageSize));
        }
        #endregion
        #region tin tức
        public ActionResult TinTuc()
        {
            return View();
        }
        #endregion
        #region giới thiệu
        public ActionResult GioiThieu()
        {
            return View();
        }
        #endregion
        #region Sản phẩm tìm kiếm (Search)
        public ActionResult Search(string id)
        {
            //Lấy ra danh sách sản phẩm từ chuỗi tìm kiếm truyền vào
            var search = (from sp in data.SANPHAMs
                          where (sp.TrangThai == true) && (sp.TenGiay.Contains(id)) && (sp.THUONGHIEU.TenThuongHieu.Contains(id))
                          orderby sp.GiaBan descending
                          select sp).ToList();

            //Lấy ra các sản phẩm khác (Không có sản phẩm của nhà sản xuất đang xem)
            ViewBag.SP_Khac = (from sp in data.SANPHAMs
                               where (sp.TrangThai == true) && (!sp.TenGiay.Contains(id)) && (sp.THUONGHIEU.TenThuongHieu.Contains(id))
                               orderby sp.GiaBan descending
                               select sp).ToList();

            //Tạo key để xuất thông báo tìm kiếm
            ViewBag.TuKhoa = id;
            return View(search);
        }
        #endregion
        #endregion
    }
}

Project_62133199/Views/Home_62133199/GiayMoi.cshtml
@model IEnumerable<Project_62133199.Models.SANPHAM>
@foreach (var item in Model)
{
    <div class="wmuSliderWrapper">
        <article style="position: relative; width: 100%; opacity: 1;">
            <div class="banner-wrap">
                <div class="slider-left">
                    <img src="~/images/@item.AnhBia" alt="" />
                </div>
                <div class="slider-right">
                    <h2>@item.TenGiay</h2>
                    <p>@String.Format("{0:0,0}", item.GiaBan) VNĐ</p>
                    <div class="btn"><a href="@Url.Action("ChiTietSanPham", "Home_62133199",new {id = item.MaGiay } )">Xem thêm</a></div>
                </div>
                <div class="clear"></div>
            </div>
        </article>
    </div>
}

Project_62133199/Views/Home_62133199/GiayNam.cshtml
@model IEnumerable<Project_62133199.Models.LOAIGIAY>
@foreach (var item in Model)
{
<ul>
    <li><a href="@Url.Action("SPTheoGioiTinh","Home_62133199",new { id = item.MaLoai})">@item.TenLoai</a></li>
</ul>
   
}

Project_62133199/Views/Home_62133199/GiayNu.cshtml
@model IEnumerable<Project_62133199.Models.LOAIGIAY>
@foreach (var item in Model)
{
<ul>
    <li><a href="@Url.Action("SPTheoGioiTinh","Home_62133199",new { id = item.MaLoai})">@item.TenLoai</a></li>
</ul>
}

Project_62133199/Views/Home_62133199/GioiThieu.cshtml
@{
    ViewBag.Title = "GioiThieu";
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}

<style>
    body {
        font-family: Arial, Helvetica, sans-serif;
        margin: 0;
    }

    html {
        box-sizing: border-box;
    }

    *, *:before, *:after {
        box-sizing: inherit;
    }

    .column {
        float: left;
        width: 33.3%;
        margin-bottom: 16px;
        padding: 0 8px;
    }

    .card {
        box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
        margin: 8px;
    }

    .about-section {
        font-weight: bold;
        font-size: 30px;
        margin: 20px 0 0 200px
    }

    .container {
        padding: 0 16px;
    }

        .container::after, .row::after {
            content: "";
            clear: both;
            display: table;
        }

    .title {
        color: grey;
    }

    .button {
        border: none;
        outline: 0;
        display: inline-block;
        padding: 8px;
        color: white;
        background-color: #000;
        text-align: center;
        cursor: pointer;
        width: 100%;
    }

        .button:hover {
            background-color: #555;
        }

    .gioithieu {
        margin: 0 200px 10px 200px;
    }

    .thanhvien {
        margin: 0 200px 10px 200px;
    }

        .thanhvien h3 {
            font-weight: bold;
            font-size: 17px;
        }
</style>

<div class="about-section">
    <h1 style="font-size: 31px">Giới thiệu</h1>
    <hr />
    <br>
</div>

<div class="gioithieu">
     <h2 style="font-size: 30px">

          Chào mừng bạn đến với Shop Giày Tôn Sách - nơi đắm chìm trong thế giới của những đôi giày không giới hạn chiều dài! Chúng tôi tự hào là địa chỉ độc đáo và độ chuyên nghiệp, mang đến cho bạn trải nghiệm mua sắm độc đáo và thú vị.
          <br />
          👟 Về Chúng Tôi:
          không chỉ là một cửa hàng giày thông thường, mà là một cộng đồng yêu thích sự độc đáo và sáng tạo. Chúng tôi cam kết cung cấp những đôi giày có độ dài vô song, phản ánh phong cách và cá tính riêng của bạn.
          <br />
          🌟 Sự Đa Dạng:
          Chúng tôi hiểu rằng mỗi người có một đôi chân độc đáo và đặc biệt. Vì vậy, tự hào sở hữu một bộ sưu tập rộng lớn với các kiểu dáng, màu sắc và chất liệu đa dạng. Cho dù bạn là người yêu thích phong cách thể thao, công sở, hay năng động, chúng tôi đều có những lựa chọn phù hợp với sở thích và nhu cầu của bạn.
          <br />
          🌈 Chất Lượng Và Độ Bền:
          Điều mà chúng tôi luôn đặt lên hàng đầu là chất lượng. Tất cả các sản phẩm tại được chọn lựa kỹ lưỡng từ những nhãn hiệu uy tín và cam kết đảm bảo độ thoải mái, bền bỉ và phản ánh xu hướng thời trang mới nhất.
          <br />
          🚚 Giao Hàng Toàn Quốc:
          Chúng tôi tự tin về dịch vụ giao hàng nhanh chóng và an toàn của mình. Bạn chỉ cần đặt hàng và chờ đợi, chúng tôi sẽ đảm bảo sản phẩm đến tay bạn một cách nhanh chóng và an toàn.
          <br />
          🤝 Cam Kết Hỗ Trợ Khách Hàng:
          Khách hàng là trung tâm của mọi hoạt động của chúng tôi. Đội ngũ hỗ trợ của luôn sẵn lòng giải đáp mọi thắc mắc và hỗ trợ bạn trong quá trình mua sắm.
          <br />
          Hãy bước chân vào để khám phá thế giới giày dài không giới hạn và tìm cho mình những đôi giày phản ánh đẳng cấp và phong cách độc đáo!
     </h2>
</div>

Project_62133199/Views/Home_62133199/Index.cshtml
@using Project_62133199.Models
@using PagedList.Mvc
@model PagedList.PagedList<SANPHAM>
<link href="~/Content/PagedList.css" rel="stylesheet" />
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}
<div class="index-banner">
    <div class="wmuSlider example1" style="height: 560px;">
        @Html.Action("GiayMoi", "Home_62133199")
        <a class="wmuSliderPrev">Previous</a><a class="wmuSliderNext">Next</a>
        <ul class="wmuSliderPagination">
            <li><a href="#" class="">0</a></li>
            <li><a href="#" class="">1</a></li>
            <li><a href="#" class="wmuActive">2</a></li>
            <li><a href="#">3</a></li>
            <li><a href="#">4</a></li>
        </ul>
        <a class="wmuSliderPrev">Previous</a><a class="wmuSliderNext">Next</a><ul class="wmuSliderPagination"><li><a href="#" class="wmuActive">0</a></li><li><a href="#" class="">1</a></li><li><a href="#" class="">2</a></li><li><a href="#" class="">3</a></li><li><a href="#" class="">4</a></li></ul>
    </div>
    <script src="~/Scripts/jquery.wmuSlider.js"></script>
    <script type="text/javascript" src="~/Scripts/modernizr.custom.min.js"></script>
    <script>
        $('.example1').wmuSlider();
    </script>
</div>
<div class="main">
    <div class="wrap">
        <div class="content-bottom" style=" padding-left: 20px; padding-right: 20px">
            @foreach (var item in Model)
            {
                if (item.TrangThai==true) 
                { 
                <div class="box1">
                    <div class="col_1_of_3 span_1_of_3" style="margin: 0 20px 20px 0">
                        <a href="@Url.Action("ChiTietSanPham", "Home_62133199",new {id = item.MaGiay } )">
                            <div class="view view-fifth">
                                <div class="top_box">
                                    <h3 class="m_1">@item.TenGiay</h3>
                                    <div class="grid_img">
                                        <div class="css3"><img src="~/images/@item.AnhBia" style="width:173px; height:173px" alt="" /></div>
                                        <div class="mask" style="text-align: center">
                                            <div class="info">Xem thêm</div>
                                        </div>
                                    </div>
                                    <div class="price">@String.Format("{0:0,0}", item.GiaBan) VNĐ</div>
                                </div>
                            </div>
                            <div class="clear"></div>
                        </a>
                    </div>
                </div>
                }
            }

            <div class="clear"></div>
            <br />
            <div class="MenuTrang" style="text-align:center">
                Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber)/@Model.PageCount
                @Html.PagedListPager(Model, page => Url.Action("Index", new { page }))
            </div>
        </div>
    </div>
</div>

Project_62133199/Views/Home_62133199/ListSanPham.cshtml
@using Project_62133199.Models
@using PagedList.Mvc
@model PagedList.PagedList<SANPHAM>
<link href="~/Content/PagedList.css" rel="stylesheet" />

@{
    ViewBag.Title = "SPTheoGioiTinh";
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}

<div class="login">
    <div class="wrap">
        <div class="List" style=" padding-left: 50px; padding-right: 50px">
            <div class="clear"></div>
            @*item *@
            <div   class="box1" style="text-align:center" >
                @foreach (var item in Model)
                {
                if (item.TrangThai==true) 
                    {
                    <div class="box1">
                        <div class="col_1_of_3 span_1_of_3" style="margin: 0 20px 20px 0">
                            <a href="@Url.Action("ChiTietSanPham", "Home_62133199",new {id = item.MaGiay } )">
                                <div class="view view-fifth">
                                    <div class="top_box">
                                        <h3 class="m_1">@item.TenGiay</h3>
                                        <div class="grid_img">
                                            <div class="css3"><img src="~/images/@item.AnhBia" style="width:173px; height:173px" alt="" /></div>
                                            <div class="mask">
                                                <div class="info">Xem thêm</div>
                                            </div>
                                        </div>
                                        <div class="price">@String.Format("{0:0,0}", item.GiaBan) VNĐ</div>
                                    </div>
                                </div>
                                <div class="clear"></div>
                            </a>
                        </div>
                    </div>
                    }
                }
                <div class="clear"></div>
            </div>
            @*end item *@
            <br />
            <div class="MenuTrang" style="text-align:center">
                Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber)/@Model.PageCount
                @Html.PagedListPager(Model, page => Url.Action("ListSanPham", new { page }))
            </div>
        </div>

        <div class="clear"></div>
    </div>
</div>

Project_62133199/Views/Home_62133199/SPTheoGioiTinh.cshtml
@using Project_62133199.Models
@using PagedList.Mvc
@model PagedList.PagedList<SANPHAM>
<link href="~/Content/PagedList.css" rel="stylesheet" />

@{
    ViewBag.Title = "SPTheoGioiTinh";
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}

<div class="login">
    <div class="wrap">
        <div class="List" style=" padding-left: 50px; padding-right: 50px">
            @*<div class="mens-toolbar">
                <div class="sort">
                    <div class="sort-by">
                        <label>Tìm kiếm</label>
                        <select>
                            <option value="">
                                Phổ biến
                            </option>
                            <option value="">
                                Giá : Cao tới thấp
                            </option>
                            <option value="">
                                Giá : Thấp tới cao
                            </option>
                        </select>
                        <a href=""><img src="images/arrow2.gif" alt="" class="v-middle"></a>
                    </div>
                </div>

                <div class="clear"></div>
            </div>*@
            <div class="clear"></div>
            @*item *@
            <div class="box1">
                @foreach (var item in Model)
                {
                    <div class="col_1_of_single1 span_1_of_single1" style="margin: 0 20px 20px 0">
                        <a href="@Url.Action("ChiTietSanPham", "Home_62133199",new {id = item.MaGiay } )">
                            <div class="view1 view-fifth1">
                                <div class="top_box">
                                    <h3 class="m_1">@item.TenGiay</h3>
                                    <p class="m_2">@item.MaThuongHieu</p>
                                    <div class="grid_img">
                                        <div class="css3"><img src="~/images/@item.AnhBia" style="width: 173px; height: 173px " alt="" /></div>
                                        <div class="mask1">
                                            <div class="info">Xem thêm</div>
                                        </div>
                                    </div>
                                    <div class="price">@String.Format("{0:0,0}", item.GiaBan) VNĐ</div>
                                </div>
                            </div>
                            <div class="clear"></div>
                        </a>
                    </div>
                }
                <div class="clear"></div>
            </div>
            @*end item *@
            <br />
            <div class="MenuTrang" style="text-align:center">
                Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber)/@Model.PageCount
                @Html.PagedListPager(Model, page => Url.Action("SPTheoGioiTinh", new { page }))
            </div>
            <div class="clear"></div>
        </div>
    </div>
</div>

Project_62133199/Views/Home_62133199/SPTheoThuongHieu.cshtml
@using Project_62133199.Models
@using PagedList.Mvc
@model PagedList.PagedList<SANPHAM>
<link href="~/Content/PagedList.css" rel="stylesheet" />

@{
    ViewBag.Title = "SPTheoThuongHieu";
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}

<div class="login">
    <div class="wrap">
        <div class="List" style=" padding-left: 50px; padding-right: 50px">
            @*<div class="mens-toolbar">
                <div class="sort">
                    <div class="sort-by">
                        <label>Tìm kiếm</label>
                        <select>
                            <option value="">
                                Phổ biến
                            </option>
                            <option value="">
                                Giá : Cao tới thấp
                            </option>
                            <option value="">
                                Giá : Thấp tới cao
                            </option>
                        </select>
                        <a href=""><img src="images/arrow2.gif" alt="" class="v-middle"></a>
                    </div>
                </div>

                <div class="clear"></div>
            </div>*@
            <div class="clear"></div>
            @*item *@
            <div class="box1">
                @foreach (var item in Model)
                {
                    <div class="col_1_of_single1 span_1_of_single1" style="margin: 0 20px 20px 0">
                        <a href="@Url.Action("ChiTietSanPham", "Home_62133199",new {id = item.MaGiay } )">
                            <div class="view1 view-fifth1">
                                <div class="top_box">
                                    <h3 class="m_1">@item.TenGiay</h3>
                                    <p class="m_2">@item.MaThuongHieu</p>
                                    <div class="grid_img">
                                        <div class="css3"><img src="~/images/@item.AnhBia" style="width:173px; height:173px" alt="" /></div>
                                        <div class="mask1">
                                            <div class="info">Xem thêm</div>
                                        </div>
                                    </div>
                                    <div class="price">@String.Format("{0:0,0}", item.GiaBan) VNĐ</div>
                                </div>
                            </div>
                            <div class="clear"></div>
                        </a>
                    </div>
                }
                <div class="clear"></div>
            </div>
            @*end item *@
            <br />
            <div class="MenuTrang" style="text-align:center">
                Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber)/@Model.PageCount
                @Html.PagedListPager(Model, page => Url.Action("SPTheoThuongHieu", new { page }))
            </div>
            <div class="clear"></div>
        </div>
    </div>
</div>

Project_62133199/Views/Home_62133199/Search.cshtml
@model IEnumerable<Project_62133199.Models.SANPHAM>
@{
    ViewBag.Title = "Search";
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}

<div class="login">
    <div class="wrap">
        <div class="List" style=" padding-left: 50px; padding-right: 50px">
            <a>Tìm kiếm sản phẩm (Có @Model.Count() sản phẩm mang tên @ViewBag.TuKhoa) </a>
            <div class="mens-toolbar">
                <div class="sort">
                    <div class="sort-by">
                        <label>Tìm kiếm</label>
                        <select>
                            <option value="">
                                Phổ biến
                            </option>
                            <option value="">
                                Giá : Cao tới thấp
                            </option>
                            <option value="">
                                Giá : Thấp tới cao
                            </option>
                        </select>
                        <a href=""><img src="images/arrow2.gif" alt="" class="v-middle"></a>
                    </div>
                </div>

                <div class="clear"></div>
            </div>
            <div class="clear"></div>
            @*item *@
            <div class="box1">

                @foreach (var item in Model)
                {
                    <div class="col_1_of_single1 span_1_of_single1" style="margin: 0 20px 20px 0">
                        <a href="@Url.Action("ChiTietSanPham", "Home_62133199",new {id = item.MaGiay } )">
                            <div class="view1 view-fifth1">
                                <div class="top_box">
                                    <h3 class="m_1">@item.TenGiay</h3>
                                    <p class="m_2">@item.MaThuongHieu</p>
                                    <div class="grid_img">
                                        <div class="css3"><img src="~/images/@item.AnhBia" style="width: 173px; height: 173px " alt="" /></div>
                                        <div class="mask1">
                                            <div class="info">Xem thêm</div>
                                        </div>
                                    </div>
                                    <div class="price">@String.Format("{0:0,0}", item.GiaBan) VNĐ</div>
                                </div>
                            </div>
                            <div class="clear"></div>
                        </a>
                    </div>
                }
                <div class="clear"></div>
            </div>
            @*end item *@
            <div class="clear"></div>
        </div>
    </div>
</div>

Project_62133199/Views/Home_62133199/ThuongHieu.cshtml
@model IEnumerable<Project_62133199.Models.THUONGHIEU>
@foreach (var item in Model)
{
    <ul>
        <li><a href="@Url.Action("SPTheoThuongHieu","Home_62133199", new { id = item.MaThuongHieu})">@item.TenThuongHieu</a></li>
    </ul>
}

Project_62133199/Views/Home_62133199/TinTuc.cshtml
@{
    ViewBag.Title = "TinTuc";
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}

<div class="about-section">
    <h1>Tin tức</h1>
    <br>
</div>

<style>
    h1 {
        font-weight: bold;
        font-size: 30px;
    }

    h2 {
        font-weight: bold;
        font-size: 20px;
    }

    html {
        box-sizing: border-box;
    }

    *, *:before, *:after {
        box-sizing: inherit;
    }

    .column {
        float: left;
        width: 33.3%;
        margin-bottom: 50px;
        padding: 0 8px;
    }

    .card {
        box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
    }

    .container {
        padding: 0 16px;
        width: 100%;
        height: 280px;
    }

        .container::after, .row::after {
            content: "";
            clear: both;
            display: table;
        }

    .title {
        color: grey;
    }

    .button {
        border: none;
        outline: 0;
        display: inline-block;
        padding: 8px;
        color: white;
        background-color: #000;
        text-align: center;
        cursor: pointer;
        width: 100%;
    }

        .button:hover {
            background-color: #555;
        }

    .row {
        margin: 0px 200px 300px 200px;
    }

    .about-section {
        font-weight: bold;
        font-size: 30px;
        margin: 20px 0 0 200px
    }
</style>
<div class="row">
    <div class="column">
        <div class="card">
            <img src="~/images/tintuc1.jpg" alt="Jane" style="width: 100%; height: 230px; ">
            <div class="container">
                <h2>CÁCH LÀM SẠCH GIẦY DA LỘN NAM, NỮ HIỆU QUẢ NHẤT</h2>
                <br>
                <p class="title">Cao Nguyen | 28/12/2021</p>
                <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

                <span class="fa fa-star checked"></span>
                <span class="fa fa-star checked"></span>
                <span class="fa fa-star checked"></span>
                <span class="fa fa-star"></span>
                <span class="fa fa-star"></span>
                <p>Những sản phẩm da lộn luôn có những sức hút khó cưỡng bởi sự cá tính và không kém phần cổ điển mà nó mang...</p>
                <br>
                <a class="elementor-post__read-more" href="https://saigonsneaker.com/lifestyle/vintage-la-gi/">  Đọc tiếp » </a>

            </div>
        </div>
    </div>

    <div class="column">
        <div class="card">
            <img src="~/images/tintuc2.jpg" alt="Mike" style="width: 100%; height: 230px; ">
            <div class="container">
                <h2>VINTAGE STYLE LÀ GÌ? HƯỚNG DẪN PHỐI ĐỒ THEO PHONG CÁCH THỜI TRANG VINTAGE</h2>
                <br>
                <p class="title">Huu Tien | 28/12/2021</p>
                <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

                <span class="fa fa-star checked"></span>
                <span class="fa fa-star checked"></span>
                <span class="fa fa-star checked"></span>
                <span class="fa fa-star"></span>
                <span class="fa fa-star"></span>
                <p>Khoảng thời gian gần đây, SaigonSneaker.com nhận được khá nhiều câu hỏi và thắc mắc về một phong cách thời trang đang dần lấy lại... </p>
                <br>
                <a class="elementor-post__read-more" href="https://saigonsneaker.com/lifestyle/vintage-la-gi/">
                    Đọc tiếp »
                </a>
            </div>
        </div>
    </div>

    <div class="column">
        <div class="card">
            <img src="~/images/tintuc3.jpg" alt="John" style=" width: 100%; height: 230px;">
            <div class="container">
                <h2>CUSTOM LÀ GÌ? CÁCH CUSTOM SNEAKER BẰNG MÀU ACRYLIC CỰC ĐẸP</h2>
                <br>
                <p class="title">Gia Hao | 28/12/2021</p>
                <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

                <span class="fa fa-star checked"></span>
                <span class="fa fa-star checked"></span>
                <span class="fa fa-star checked"></span>
                <span class="fa fa-star"></span>
                <span class="fa fa-star"></span>
                <p>Custom giày là một xu hướng đã du nhập vào Việt Nam một thời gian và nhận được sự hưởng ứng mạnh từ các bạn...</p>
                <br>
                <a class="elementor-post__read-more" href="https://saigonsneaker.com/lifestyle/cach-custom-giay-tai-nha/">
                    Đọc tiếp »
                </a>
            </div>
        </div>
    </div>
</div>