Project_62133199/Controllers/DonHang_62133199Controller.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using Project_62133199.Models;

namespace Project_62133199.Controllers
{
    public class DonHang_62133199Controller : Controller
    {
        dbShopGiayDataContext data = new dbShopGiayDataContext();

        // GET: DonHang
        public ActionResult LichSuDonHang()
        {
            if (Session["Taikhoan"] == null)
            {
                return RedirectToAction("Dangnhap", "User_62133199");
            }
            else
            {
                KHACHHANG kh = (KHACHHANG)Session["Taikhoan"];
                var listLichSuDonHang = data.DONHANGs.Where(p => p.MaKH == kh.MaKH).ToList();
                return View(listLichSuDonHang);
            }

        }
        public ActionResult ChiTietDonHang(int? maDonHang, decimal? tongTien)
        {
            if (Session["Taikhoan"] == null) RedirectToAction("Index", "Home_62133199");
            KHACHHANG kh = (KHACHHANG)Session["Taikhoan"];
            var ListChiTietDonHang = data.CT_DONHANGs.Where(p => p.MaDonHang == maDonHang).ToList();  // danh sách các sản phẩm trong chi tiết đơn hàng

            List<CTDH_62133199> listCTDH = new List<CTDH_62133199>();

            foreach (var item in ListChiTietDonHang)
            {
                listCTDH.Add(new CTDH_62133199(item.MaGiay, maDonHang));
            }
            ViewBag.TongTien = tongTien;
            return View(listCTDH);
        }
    }
}

Project_62133199/Views/DonHang_62133199/ChiTietDonHang.cshtml
@using Project_62133199.Models;
@model List<CTDH_62133199>

@{
    ViewBag.Title = "OrderDetail";
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}
<style>
    td {
        padding: 13px;
        border: 1px solid black;
        text-align: center;
    }

    h2 {
        font-weight: bold;
        font-size: 30px;
        margin: 20px 0 20px 0;
    }

    .item {
        height: 100px;
    }

    .button {
        background-color: #4CAF50;
        border: none;
        color: white;
        padding: 7px 15px;
        text-align: center;
        text-decoration: none;
        display: inline-block;
        font-size: 16px;
        margin: 4px 2px;
        cursor: pointer;
    }
</style>
<h2 style=" text-align:center"> Chi tiết đơn đặt hàng </h2>
<table text-align="center" border="1" style="margin: auto">

    <tr style="text-align:center; font-weight:bold">
        <td> Mã Giày </td>
        <td width="200">Tên Giày</td>
        <td>Ảnh</td>
        <td>Size</td>
        <td>Số Lượng</td>
        <td>Giá lúc bán</td>
        <td>Thành Tiền</td>
        <td></td>
    </tr>


    @foreach (var item in Model)
    {
        <tr class="rem1">
            <td>@item.iMaGiay</td>
            <td>@item.iTenGIay</td>
            <td>
                <img src="~/images/@item.iAnhBia" style="width:100%; height:100px" />
            </td>
            <td>@item.iSize</td>
            <td>@item.iSoLuong</td>
            <td>@String.Format("{0:##,#}", item.iGiaLucBan) VNĐ</td>
            <td>@String.Format("{0:##,#}", item.iThanhTien) VNĐ</td>
            <td> <a href="@Url.Action("ChiTietSanPham", "Home_62133199", new {id = item.iMaGiay})">Chi tiết</a></td>
        </tr>

    }
    <tr>
        <td colspan="8"> Tổng tiền: @String.Format("{0:0,0}", @ViewBag.TongTien) VND </td>
    </tr>
</table>
<br />
<div style=" text-align:center; margin-bottom: 150px" >
    <a href="@Url.Action("LichSuDonHang", "DonHang_62133199")" class="button">Trở về</a>
</div>

Project_62133199/Views/DonHang_62133199/LichSuDonHang.cshtml
@using Project_62133199.Models;
@model List<DONHANG>

@{
    ViewBag.Title = "OrderHistory";
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}
<style>
    td {
        padding: 13px;
        border: 1px solid black;
        text-align: center;
    }

    h2 {
        font-weight: bold;
        font-size: 30px;
        margin: 20px 0 20px 0;
    }

    .item {
        height: 100px;
    }

    .button {
        background-color: #4CAF50;
        border: none;
        color: white;
        padding: 7px 15px;
        text-align: center;
        text-decoration: none;
        display: inline-block;
        font-size: 16px;
        margin: 4px 2px;
        cursor: pointer;
    }
</style>

<!--Lich su don hang-->

<h2 style=" text-align:center"> Lịch sử đặt hàng </h2>
<table text-align="center" border="1" style="margin: auto; margin-bottom:200px">
    <tr style="text-align:center; font-weight:bold">
        <td>Mã Đơn Hàng</td>
        <td>Ngày Đặt</td>
        <td>Ngày Giao Dự Kiến</td>
        <td>Tình Trạng Đơn Hàng</td>
        <td>Tổng Tiền</td>
        <td></td>
    </tr>

    @foreach (var item in Model)
    {
        <tr class="rem1">
            <td class="invert">@item.MaDonHang</td>
            <td class="invert">@String.Format("{0:dd/MM/yyyy}", item.NgayDat)</td>
            <td class="invert">@String.Format("{0:dd/MM/yyyy}", item.NgayGiao)</td>
            @if ((bool)item.TinhTrangGiaoHang)
            {
                <td class="invert" style="color: green"><i class="fa fa-check-square-o" aria-hidden="true" style="margin-right: 5px"></i>Đã Giao hàng</td>
            }
            else
            {
                <td class="invert" style="color: #EF4444"><i class="fa fa-truck" aria-hidden="true" style="margin-right: 5px"></i>Đang Vận Chuyển</td>
            }
            <td class="invert">@String.Format("{0:##,#}", item.TongTien) VNĐ</td>
            <td class="invert">
                <a href="@Url.Action("ChiTietDonHang","DonHang_62133199", new { maDonHang = item.MaDonHang, tongTien = item.TongTien})" class="btn btn-success">Chi Tiết Đơn Hàng</a>
            </td>
        </tr>
    }

</table>